apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: AKIAZHCJWMA3Z62VSJYX
  access_key_secret: 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
  bucketnames: loki-bucket
  endpoint: https://s3.eu-west-1.amazonaws.com
  region: eu-west-1