---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-odf
  name: app-ocp-odf
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops-argocd-apps/odf_kustomize/overlays/odf416
    repoURL: https://github.com/javierbareapalma/ocp4-odf-installation.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
