---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeling-odf-nodes
rules:
- apiGroups:
  - v1
  #- config.openshift.io/v1
  #- storage.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  
