---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa-job-labeling-odf-nodes.yml
  - cr-labeling-odf-nodes.yml
  - crb-labeling-odf-nodes.yml
  - job-labeling-odf-nodes.yml
    