---
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: kubernetes-nmstate-operator.openshift-nmstate
  namespace: openshift-nmstate
spec: 
  targetNamespaces:
    - openshift-nmstate
  #upgradeStrategy: Default
