---
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec: 
  targetNamespaces:
    - openshift-nmstate
  upgradeStrategy: Default
